"use client";

import type { ProviderName } from "@/lib/admin/providers/types";

const PROVIDER_LABELS: Record<ProviderName, string> = {
  openai: "GPT Image 1",
  gemini: "Gemini Pro",
  seedream: "Seedream 4",
};

interface HistoryItem {
  id: string;
  provider: ProviderName;
  base64: string;
  mimeType: string;
  durationMs: number;
  prompt: string;
}

interface Props {
  item: HistoryItem;
  isActive: boolean;
  onClick: () => void;
  onEdit: () => void;
  onSave: () => void;
}

export default function ImageCard({ item, isActive, onClick, onEdit, onSave }: Props) {
  return (
    <div
      className={`cursor-pointer rounded-lg overflow-hidden border-2 transition-all
        ${isActive ? "border-gold shadow-lg" : "border-transparent hover:border-rose-gray/40"}`}
      onClick={onClick}
    >
      <div className="relative aspect-square bg-white">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={`data:${item.mimeType};base64,${item.base64}`}
          alt={`Generated by ${PROVIDER_LABELS[item.provider]}`}
          className="w-full h-full object-cover"
        />
        <span className="absolute top-1 left-1 text-[10px] bg-charcoal/70 text-white px-1.5 py-0.5 rounded">
          {PROVIDER_LABELS[item.provider]}
        </span>
        <span className="absolute top-1 right-1 text-[10px] bg-charcoal/70 text-white px-1.5 py-0.5 rounded">
          {(item.durationMs / 1000).toFixed(1)}s
        </span>
      </div>
      {isActive && (
        <div className="flex gap-1 p-1.5 bg-white">
          <button
            onClick={(e) => { e.stopPropagation(); onEdit(); }}
            className="flex-1 text-xs py-1.5 bg-burgundy/10 text-burgundy rounded hover:bg-burgundy/20 transition-colors"
          >
            Edit
          </button>
          <button
            onClick={(e) => { e.stopPropagation(); onSave(); }}
            className="flex-1 text-xs py-1.5 bg-gold/10 text-gold rounded hover:bg-gold/20 transition-colors font-medium"
          >
            Save
          </button>
        </div>
      )}
    </div>
  );
}

export type { HistoryItem };
