"use client";

import type { ProviderName } from "@/lib/admin/providers/types";
import ImageCard from "./ImageCard";
import type { HistoryItem } from "./ImageCard";

const PROVIDER_LABELS: Record<ProviderName, string> = {
  openai: "GPT Image 1",
  gemini: "Gemini Pro",
  seedream: "Seedream 4",
};

interface Props {
  history: HistoryItem[];
  activeId: string | null;
  onSelect: (id: string) => void;
  onEdit: (id: string) => void;
  onSave: (id: string) => void;
  loading: boolean;
  loadingProvider: ProviderName | null;
}

export default function ResultsGallery({
  history,
  activeId,
  onSelect,
  onEdit,
  onSave,
  loading,
  loadingProvider,
}: Props) {
  const activeItem = history.find((h) => h.id === activeId);

  if (!activeItem && !loading && history.length === 0) {
    return (
      <div className="rounded-xl border-2 border-dashed border-rose-gray/30 p-12 text-center">
        <p className="text-rose-gray text-lg">No images generated yet</p>
        <p className="text-rose-gray/60 text-sm mt-1">
          Enter a prompt and click Generate to get started
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {/* Main display — active image or loading state */}
      <div className="rounded-xl overflow-hidden bg-white shadow-sm border border-rose-gray/10">
        {loading && !activeItem ? (
          <div className="aspect-square max-h-[512px] mx-auto flex flex-col items-center justify-center bg-parchment animate-pulse">
            <div className="w-12 h-12 border-4 border-burgundy/30 border-t-burgundy rounded-full animate-spin" />
            <p className="mt-4 text-rose-gray text-sm">
              Generating with {loadingProvider ? PROVIDER_LABELS[loadingProvider] : "..."}
            </p>
          </div>
        ) : activeItem ? (
          <div className="relative">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={`data:${activeItem.mimeType};base64,${activeItem.base64}`}
              alt={`Generated by ${PROVIDER_LABELS[activeItem.provider]}`}
              className="w-full max-h-[512px] object-contain mx-auto"
            />
            <div className="absolute top-3 left-3 flex gap-2">
              <span className="text-xs bg-charcoal/70 text-white px-2 py-1 rounded-full">
                {PROVIDER_LABELS[activeItem.provider]}
              </span>
              <span className="text-xs bg-charcoal/70 text-white px-2 py-1 rounded-full">
                {(activeItem.durationMs / 1000).toFixed(1)}s
              </span>
            </div>
            {loading && (
              <div className="absolute inset-0 bg-white/60 flex items-center justify-center">
                <div className="w-10 h-10 border-4 border-burgundy/30 border-t-burgundy rounded-full animate-spin" />
              </div>
            )}
            <div className="flex gap-2 p-3 border-t border-rose-gray/10">
              <button
                onClick={() => onEdit(activeItem.id)}
                className="px-4 py-2 bg-burgundy/10 text-burgundy rounded-lg text-sm hover:bg-burgundy/20 transition-colors"
              >
                Edit (Inpaint)
              </button>
              <button
                onClick={() => onSave(activeItem.id)}
                className="px-4 py-2 bg-gold/10 text-gold rounded-lg text-sm hover:bg-gold/20 transition-colors font-medium"
              >
                Save to Cloudinary
              </button>
            </div>
          </div>
        ) : null}
      </div>

      {/* Thumbnail strip */}
      {history.length > 0 && (
        <div>
          <h3 className="text-sm font-medium text-charcoal mb-2">
            Generation History ({history.length})
          </h3>
          <div className="flex gap-2 overflow-x-auto pb-2">
            {history.map((item) => (
              <div key={item.id} className="flex-shrink-0 w-24">
                <ImageCard
                  item={item}
                  isActive={item.id === activeId}
                  onClick={() => onSelect(item.id)}
                  onEdit={() => onEdit(item.id)}
                  onSave={() => onSave(item.id)}
                />
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
